"""empty message

Revision ID: a61fa617b3a3
Revises: c4e9dfcbf247
Create Date: 2021-08-11 13:10:10.982370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61fa617b3a3'
down_revision = 'c4e9dfcbf247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('City', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('City', sa.Column('state', sa.String(length=120), nullable=False))
    op.drop_column('City', 'city_name')
    op.drop_column('City', 'city_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('City', sa.Column('city_state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('City', sa.Column('city_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('City', 'state')
    op.drop_column('City', 'name')
    # ### end Alembic commands ###
