"""empty message

Revision ID: e53c0c9d459a
Revises: 9262ba1d9e91
Create Date: 2021-08-11 18:17:46.729601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'e53c0c9d459a'
down_revision = '9262ba1d9e91'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genres_table = table("Genre",
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String))
    op.bulk_insert(genres_table,
        [
            {'id':1, 'name':'Jazz'},
            {'id':2, 'name':'Reggae'},
            {'id':3, 'name':'Swing'},
            {'id':4, 'name':'Classical'},
            {'id':5, 'name':'Folk'},
            {'id':6, 'name':'R&B'},
            {'id':7, 'name':'Hip-Hop'},
            {'id':8, 'name':'Rock n Roll'},
        ]
    )

    cities_table=table("City",
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(120)),
        sa.Column('state', sa.String(120))
    )
    op.bulk_insert(cities_table,
        [
            {'id':1, 'name':'San Francisco', 'state':'CA'},
            {'id':2, 'name':'New York', 'state':'NY'}
        ]
    )

    artists_table=table("Artist",
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('city_id', sa.Integer, sa.ForeignKey('City.id'), nullable=False),
        sa.Column('phone', sa.String(120)),
        sa.Column('image_link', sa.String(500)),
        sa.Column('facebook_link', sa.String(120)),
        sa.Column('website', sa.String),
        sa.Column('seeking_venue', sa.Boolean, nullable=False),
        sa.Column('seeking_description', sa.String(3000))
    )
    op.bulk_insert(artists_table,
        [
            {
                'id':1,
                'name':'Guns N Petals',
                'city_id':1,
                'phone':'326-123-5000',
                'image_link':'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80',
                'facebook_link':'https://www.facebook.com/GunsNPetals',
                'website':'https://www.gunsnpetalsband.com',
                'seeking_venue':True,
                'seeking_description':'Looking for shows to perform at in the San Francisco Bay Area!'
            },
            {
                'id':2,
                'name':'Matt Quevedo',
                'city_id':2,
                'phone':'300-400-5000',
                'image_link':'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80',
                'facebook_link':'https://www.facebook.com/mattquevedo923251523',
                'website':"",
                'seeking_venue':False,
                'seeking_description':""
            },
            {
                'id':3,
                'name':'The Wild Sax Band',
                'city_id':1,
                'phone':'432-325-5432',
                'image_link':'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80',
                'facebook_link':'',
                'website':'',
                'seeking_venue':False,
                'seeking_description':''
            }
        ]
    )

    artist_genres=table('artist_genres',
        sa.Column('artist_id', sa.Integer, sa.ForeignKey('Artist.id'), primary_key=True),
        sa.Column('genre_id', sa.Integer, sa.ForeignKey('Genre.id'), primary_key=True)
    )
    op.bulk_insert(artist_genres,
        [
            {'artist_id':1, 'genre_id':8},
            {'artist_id':2, 'genre_id':1},
            {'artist_id':3, 'genre_id':1},
            {'artist_id':3, 'genre_id':4}
        ]
    )

    venues = table('Venue',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('city_id', sa.Integer, sa.ForeignKey('City.id'), nullable=False),
        sa.Column('address', sa.String(120), nullable=False),
        sa.Column('phone', sa.String(120)),
        sa.Column('image_link', sa.String(500)),
        sa.Column('facebook_link', sa.String(120)),
        sa.Column('website', sa.String),
        sa.Column('seeking_talent', sa.Boolean, nullable=False),
        sa.Column('seeking_description', sa.String(3000))
    )
    op.bulk_insert(venues,
        [
            {
                'id': 1,
                'name': 'The Musical Hop',
                'city_id': 1,
                'address': '1015 Folsom Street',
                'phone': '123-123-1234',
                'image_link': 'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
                'facebook_link': 'https://www.facebook.com/TheMusicalHop',
                'website': 'https://www.themusicalhop.com',
                'seeking_talent': True,
                'seeking_description': 'We are on the lookout for a local artist to play every two weeks. Please call us.'
            },
            {
                'id': 2,
                'name': 'The Dueling Pianos Bar',
                'city_id': 2,
                'address': '335 Delancey Street',
                'phone': '914-003-1132',
                'image_link': 'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',
                'facebook_link': 'https://www.facebook.com/theduelingpianos',
                'website': 'https://www.theduelingpianos.com',
                'seeking_talent': False,
                'seeking_description': ''
            },
            {
                'id': 3,
                'name': 'Park Square Live Music & Coffee',
                'city_id': 1,
                'address': '34 Whiskey Moore Ave',
                'phone': '415-000-1234',
                'image_link': 'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80',
                'facebook_link': 'https://www.facebook.com/ParkSquareLiveMusicAndCoffee',
                'website': 'https://www.parksquarelivemusicandcoffee.com',
                'seeking_talent': False,
                'seeking_description': ''
            }
        ]
    )

    venue_genres=table('venue_genres',
        sa.Column('venue_id', sa.Integer, sa.ForeignKey('Venue.id'), primary_key=True),
        sa.Column('genre_id', sa.Integer, sa.ForeignKey('Genre.id'), primary_key=True)
    )
    op.bulk_insert(venue_genres,
        [
            {'venue_id':1, 'genre_id':1},
            {'venue_id':1, 'genre_id':2},
            {'venue_id':1, 'genre_id':3},
            {'venue_id':1, 'genre_id':4},
            {'venue_id':1, 'genre_id':5},
            {'venue_id':2, 'genre_id':4},
            {'venue_id':2, 'genre_id':6},
            {'venue_id':2, 'genre_id':7},
            {'venue_id':3, 'genre_id':8},
            {'venue_id':3, 'genre_id':1},
            {'venue_id':3, 'genre_id':4},
            {'venue_id':3, 'genre_id':5},
        ]
    )

    shows=table('Show', 
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('venue_id', sa.Integer, sa.ForeignKey('Venue.id'), nullable=False),
        sa.Column('artist_id', sa.Integer, sa.ForeignKey('Artist.id'), nullable=False),
        sa.Column('start_time', sa.DateTime, nullable=False)
    )
    op.bulk_insert(shows,
        [
            {'id':1, 'venue_id':1, 'artist_id':1, 'start_time':'2019-05-21T21:30:00.000Z'},
            {'id':2, 'venue_id':3, 'artist_id':2, 'start_time':'2019-06-15T23:00:00.000Z'},
            {'id':3, 'venue_id':3, 'artist_id':3, 'start_time':'2035-04-01T20:00:00.000Z'},
            {'id':4, 'venue_id':3, 'artist_id':3, 'start_time':'2035-04-08T20:00:00.000Z'},
            {'id':5, 'venue_id':3, 'artist_id':3, 'start_time':'2035-04-15T20:00:00.000Z'}
        ]
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "artist_genres" WHERE 1 = 1')
    op.execute('DELETE FROM "venue_genres" WHERE 1 = 1')
    op.execute('DELETE FROM "Genre" WHERE 1 = 1')
    op.execute('DELETE FROM "Show" WHERE 1 = 1')
    op.execute('DELETE FROM "Artist" WHERE 1 = 1')
    op.execute('DELETE FROM "Venue" WHERE 1 = 1')
    op.execute('DELETE FROM "City" WHERE 1 = 1')
    # ### end Alembic commands ###
